name: Run Python Script

on:
  push:
    branches:
      - main  # Trigger on push to the main branch
    branches:
        - MP  # Trigger on Push to MP branch
  schedule:
    - cron: '0 0 * * *' # Run daily at midnight UTC

jobs:
  build:
    runs-on: ubuntu-latest # Specify the operating system for the runner

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9' # Specify the Python version

      - name: Install dependencies
        run: pip install -r requirements.txt # Install packages from requirements.txt (if applicable)

      - name: Run Python script
        run: python app.py # Execute your Python script